name: build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          cache: yarn
          # https://www.npmjs.com/package/selenium-webdriver#projected-support-schedule
          node-version-file: .nvmrc

      - name: Install dependencies
        run: yarn --frozen-lockfile --prefer-offline

      - name: Run async-await
        run: yarn async-await

      - name: Run build
        run: node -e 'require("./recipes/build").quit()'

      - name: Run chrome-profile
        run: yarn chrome-profile

      - name: Run cucumber
        run: yarn cucumber

      - name: Run find
        run: yarn find

      - name: Run jest
        run: yarn jest

      - name: Run mocha
        run: yarn mocha

      - name: Run screenshot
        run: yarn screenshot

      - name: Run wait-until
        run: yarn wait-until
